version: '3.8'

services:
  # Neon Local - Database proxy service
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development

    volumes:
      # Optional: For persistent branch per git branch
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost', '-p', '5432', '-U', 'neon']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - acquisitions-network

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      # Mount source code for development (optional - for hot reload)
      - ./src:/app/src:ro
      - ./logs:/app/logs
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-network
    restart: unless-stopped

  # Optional: PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: acquisitions-pgadmin
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@acquisitions.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - acquisitions-network
    profiles:
      - tools # Only start with --profile tools

networks:
  acquisitions-network:
    driver: bridge
    name: acquisitions-dev-network

volumes:
  pgadmin-data:
    driver: local
