name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    name: Lint and Prettier
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: npm run lint

      - name: Run Prettier (check)
        id: prettier
        continue-on-error: true
        run: npm run format:check

      - name: Summarize results and annotate
        if: always()
        shell: pwsh
        run: |
          $lintOk = '${{ steps.eslint.outcome }}' -eq 'success'
          $fmtOk  = '${{ steps.prettier.outcome }}' -eq 'success'

          if ($lintOk -and $fmtOk) {
            @"
          ✅ Lint and format checks passed.

          - ESLint: OK
          - Prettier: OK
          "@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          else {
            if (-not $lintOk) {
              Write-Output "::error title=ESLint issues detected::Run 'npm run lint:fix' locally to auto-fix where possible, then commit."
            }
            if (-not $fmtOk) {
              Write-Output "::error title=Prettier formatting issues detected::Run 'npm run format' locally to format files, then commit."
            }

            @"
          ❌ Lint and/or format checks failed.

          Suggested fixes:
          - Run: npm run lint:fix
          - Run: npm run format

          ESLint status: $([bool]$lintOk)
          Prettier status: $([bool]$fmtOk)
          "@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

            exit 1
          }
